[package]
name = "analytics-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal crates
common = { path = "../common" }

# External crates
lazy_static = "1.5.0"
sqlparser = "0.58.0"
tracing-subscriber = "0.3.19"
