[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal crates
common = { path = "../../core/common" }
analytics-core = { path = "../../core/analytics" }

# Crates
axum = "0.8.4"
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
